left = ["loadavg", "ram"]
center = ["xworkspaces"]
right = ["date"]

separator = " | "

frontend = "lemonbar"

[modules.date]
interval = 1
icon = "DAT "
icon_color = "#866fc1"
format = "%H:%M:%S"

[modules.loadavg]
interval = 1
icon = "LA "
icon_color = "#866fc1"
format = "{1m} {5m} {15m} {total}"
