left = ["loadavg", "memory", "wpctl", "filesystem"]
center = ["xworkspaces"]
right = ["date"]

separator = " | "

frontend = "lemonbar"

[modules.date]
interval = 1
icon = "DAT "
icon_color = "#866fc1"
format = "%H:%M:%S"

[modules.filesystem]
interval = 1
icon = "FS "
icon_color = "#866fc1"
format = "{mount}: {%_used}% used ({gib_used}GiB/{gib_total}GiB)"
mountpoint = "/"

[modules.loadavg]
interval = 1
icon = "LA "
icon_color = "#866fc1"
format = "{1m} {5m} {15m} {total}"

[modules.memory]
interval = 1
icon = "MEM "
icon_color = "#866fc1"
format = "{mib}MiB ({%}%)"

[modules.wpctl]
interval = 1
icon = "VOL "
icon_color = "#866fc1"
format = "{volume}%"
format_muted = "MUTED ({volume}%)"
